/**
 * Maps each form field to the editor tab that holds it, so a blocked save can
 * open the right tab and scroll to the offending input.
 *
 * Keys are root field names (the part before the first dot), which is enough:
 * every element of `tiers[]` lives on the Tiers tab, and so on. Anything not
 * listed falls back to the editor's first tab.
 */

export const PACKAGE_FIELD_TAB = {
  name: "Basics",
  region: "Basics",
  season: "Basics",
  duration: "Basics",
  duration_days: "Basics",
  hero_image: "Basics",
  card_image: "Basics",
  min_people: "Basics",
  max_people: "Basics",
  available_from: "Basics",
  available_to: "Basics",
  is_published: "Basics",
  is_featured: "Basics",
  short_description: "Overview",
  overview: "Overview",
  itinerary: "Itinerary",
  tiers: "Tiers",
  gallery: "Gallery",
  included: "Inclusions",
  not_included: "Inclusions",
} as const;

export const PREMADE_FIELD_TAB = {
  name: "Basics",
  dates: "Basics",
  destinations: "Basics",
  short_description: "Basics",
  currency: "Basics",
  is_published: "Basics",
  region: "Overview",
  season: "Overview",
  duration: "Overview",
  min_people: "Overview",
  max_people: "Overview",
  available_from: "Overview",
  available_to: "Overview",
  overview: "Overview",
  price_1_person: "Overview",
  price_baby: "Overview",
  itinerary: "Itinerary",
  tiers: "Tiers",
  included: "Inclusions",
  not_included: "Inclusions",
  hero_image: "Imagery",
  card_image: "Imagery",
  gallery: "Imagery",
  accommodation_name: "Accommodation",
  accommodation_description: "Accommodation",
  accommodation_image_a: "Accommodation",
  accommodation_image_b: "Accommodation",
  vehicle_model: "Vehicle",
  vehicle_features: "Vehicle",
} as const;

export const DAILY_FIELD_TAB = {
  name: "Basics",
  tour_date: "Basics",
  start_time: "Basics",
  end_time: "Basics",
  region: "Basics",
  season: "Basics",
  vehicle: "Basics",
  driver: "Basics",
  short_description: "Basics",
  is_published: "Basics",
  price: "Pricing",
  currency: "Pricing",
  price_1_person: "Pricing",
  price_2_people: "Pricing",
  price_baby: "Pricing",
  price_single_room_supplement: "Pricing",
  price_per_child: "Pricing",
  hero_image: "Imagery",
  card_image: "Imagery",
  gallery: "Imagery",
  stops: "Itinerary",
  included: "Inclusions",
  not_included: "Inclusions",
} as const;

export const HOTEL_FIELD_TAB = {
  name: "Basics",
  region: "Basics",
  description: "Basics",
  long_description: "Basics",
  tag_a: "Basics",
  tag_b: "Basics",
  stars: "Basics",
  svg_variant: "Basics",
  location: "Basics",
  is_published: "Basics",
  check_in_time: "Properties",
  check_out_time: "Properties",
  languages: "Properties",
  distance_km: "Properties",
  bedrooms: "Properties",
  bathrooms: "Properties",
  free_wifi: "Amenities",
  free_cancellation: "Amenities",
  free_parking: "Amenities",
  bed_breakfast: "Amenities",
  balcony: "Amenities",
  washer: "Amenities",
  ac: "Amenities",
  tv: "Amenities",
  amenities: "Amenities",
  room_types: "Room Types",
  images: "Gallery",
} as const;
